const state = { assembly: [], models: [], vaultStatus: null, vaults: [], anomalies: null, cases: [], caseId: null, overview: null, observations: [], detail: null, timeline: [], graph: { nodes: [], edges: [], groups: [] }, profiles: [], processing: [], findings: [], imports: [] };
const byId = (id) => document.getElementById(id);
const statusNode = byId("processing-status");
let apiToken = sessionStorage.getItem("sithassembly-api-token") || "";
let tokenPrompt = null;
function setStatus(message, error = false) { statusNode.textContent = message; statusNode.dataset.error = String(error); }
function requestApiToken() { if (!tokenPrompt) tokenPrompt = Promise.resolve().then(() => window.prompt("API access token") || "").then((value) => { apiToken = value.trim(); if (apiToken) sessionStorage.setItem("sithassembly-api-token", apiToken); else sessionStorage.removeItem("sithassembly-api-token"); return apiToken; }).finally(() => { tokenPrompt = null; }); return tokenPrompt; }
async function authenticatedFetch(path, options = {}, retried = false) { const headers = new Headers(options.headers || {}); headers.set("Accept", "application/json"); if (options.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json"); if (apiToken) headers.set("Authorization", `Bearer ${apiToken}`); const response = await fetch(path, { ...options, headers }); if (response.status !== 401 || retried) return response; sessionStorage.removeItem("sithassembly-api-token"); apiToken = ""; if (!await requestApiToken()) return response; return authenticatedFetch(path, options, true); }
async function api(path, options = {}) { const response = await authenticatedFetch(path, options); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || `HTTP ${response.status}`); return payload; }
async function downloadApi(path, fallbackName = "sithassembly-export") { const response = await authenticatedFetch(path); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw new Error(payload.error || `HTTP ${response.status}`); } const disposition = response.headers.get("Content-Disposition") || ""; const matchedName = disposition.match(/filename="([^"\\/]+)"/i)?.[1]; const objectUrl = URL.createObjectURL(await response.blob()); const anchor = document.createElement("a"); anchor.href = objectUrl; anchor.download = matchedName || fallbackName; anchor.click(); setTimeout(() => URL.revokeObjectURL(objectUrl), 1000); }
function esc(value) { return String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character])); }
function safeExternalUrl(value) { try { const parsed = new URL(String(value ?? "")); return ["http:", "https:"].includes(parsed.protocol) && !parsed.username && !parsed.password ? parsed.href : ""; } catch { return ""; } }
function safeApiPath(value) { try { const parsed = new URL(String(value ?? ""), window.location.origin); return parsed.origin === window.location.origin && parsed.pathname.startsWith("/api/") ? `${parsed.pathname}${parsed.search}` : ""; } catch { return ""; } }
function risk(score) { if (score >= 70) return "critical"; if (score >= 45) return "high"; if (score >= 20) return "moderate"; return "low"; }
function formatTime(value) { if (!value) return "no timestamp"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" }); }
function queryPath() { const params = new URLSearchParams(); const q = byId("search-input").value.trim(); const minRisk = byId("risk-filter").value; if (q) params.set("q", q); if (minRisk) params.set("min_risk", minRisk); const suffix = params.toString(); return `/api/cases/${state.caseId}/observations${suffix ? `?${suffix}` : ""}`; }
function renderCases() { byId("case-list").innerHTML = state.cases.map((item) => `<button type="button" class="case-card ${item.id === state.caseId ? "active" : ""}" data-case-id="${item.id}"><strong>${esc(item.title)}</strong><span>${item.observation_count} observations · ${item.evidence_count} evidence records</span></button>`).join("") || '<p class="empty">No case has been created.</p>'; document.querySelectorAll("[data-case-id]").forEach((button) => button.addEventListener("click", () => selectCase(Number(button.dataset.caseId)))); }
function renderOverview() { const current = state.overview?.case; if (!current) return; byId("case-title").textContent = current.title; byId("case-description").textContent = current.description || "No case description."; byId("case-state").textContent = `Status: ${current.status} · updated ${formatTime(current.updated_at)}`; byId("metrics").innerHTML = [["Observations", current.observation_count], ["Evidence", current.evidence_count], ["Relationships", current.relationship_count], ["Profiles", state.profiles.length]].map(([label, value]) => `<div class="metric"><strong>${value}</strong><span>${label}</span></div>`).join(""); }
function renderProcessing() { byId("processing-list").innerHTML = state.processing.slice(0, 8).map((item) => `<article class="processing-item"><span class="stage">${esc(item.stage)}</span><p>${esc(item.message)}</p><small>${formatTime(item.created_at)}${item.confidence !== null ? ` · ${Math.round(item.confidence * 100)}%` : ""}</small></article>`).join("") || '<p class="empty">No processing events yet.</p>'; }
function renderObservations() { byId("observation-count").textContent = `${state.observations.length} matches`; byId("observation-list").innerHTML = state.observations.map((item) => `<button type="button" class="observation-card ${state.detail?.observation.id === item.id ? "active" : ""}" data-observation-id="${item.id}"><div><strong>${esc(item.actor_handle)}</strong><span class="risk ${risk(item.risk_level)}">${risk(item.risk_level)} ${item.risk_level}/100</span></div><p>${esc(item.body)}</p><small>${formatTime(item.captured_at)} · ${item.tags.map(esc).join(" ")}</small></button>`).join("") || '<p class="empty">No matches for this filter.</p>'; document.querySelectorAll("[data-observation-id]").forEach((button) => button.addEventListener("click", () => selectObservation(Number(button.dataset.observationId)))); }
function link(label, url) { const safeUrl = safeExternalUrl(url); return safeUrl ? `<a href="${esc(safeUrl)}" target="_blank" rel="noreferrer">${esc(label || safeUrl)}</a>` : `<span>${esc(label || "Local evidence")}</span>`; }
function renderDetail() { const detail = state.detail; byId("detail-empty").hidden = Boolean(detail); byId("detail-content").hidden = !detail; byId("generate-draft").disabled = !detail; if (!detail) return; const { observation, actor, evidence, relationships, tags, draft, ocr_runs: ocrRuns = [] } = detail; byId("detail-summary").innerHTML = `<div><span class="handle">${esc(actor.handle)} · ${esc(actor.platform)}</span><span class="risk ${risk(observation.risk_level)}">${risk(observation.risk_level)} ${observation.risk_level}/100</span></div><p>${esc(observation.body)}</p>${link(observation.source_url, observation.source_url)}<small>Captured: ${formatTime(observation.captured_at)}</small>`; const allTags = [...tags.map((tag) => tag.label), ...observation.danger_flags]; byId("detail-tags").innerHTML = allTags.map((tag) => `<span class="tag">${esc(tag)}</span>`).join("") || '<span class="muted">No tags.</span>'; byId("detail-evidence").innerHTML = evidence.map((item) => `<article><div>${link(item.label, item.url)}</div><p>${esc(item.annotation)}</p>${item.kind === "local_image" ? `<button type="button" data-ocr-evidence="${item.id}">Run OCR</button>` : ""}<small>${formatTime(item.captured_at)} · ${esc(item.kind)}</small></article>`).join("") || '<p class="empty">No evidence records.</p>'; byId("detail-relationships").innerHTML = relationships.map((item) => `<article><strong>${esc(item.relation_type)} → ${esc(item.target_handle)}</strong><p>Confidence ${Math.round(Number(item.weight) * 100)}% · Evidence: ${link("Open observation", observation.source_url)}</p></article>`).join("") || '<p class="empty">No relationships.</p>'; byId("detail-ocr").innerHTML = ocrRuns.map((run) => `<article><strong>${esc(run.profile)} · ${esc(run.state)}</strong><p>${esc(run.text || run.result?.message || "No text extracted.")}</p><small>${formatTime(run.created_at)}</small></article>`).join("") || '<p class="empty">Store local image evidence and run OCR explicitly.</p>'; byId("detail-draft").textContent = draft?.body || "No draft created. Source-bound drafts remain pending human review."; document.querySelectorAll("[data-ocr-evidence]").forEach((button) => button.addEventListener("click", () => runOcr(Number(button.dataset.ocrEvidence)))); }
function renderTimeline() { byId("timeline").innerHTML = state.timeline.slice(0, 30).map((item) => `<button type="button" class="timeline-event" data-timeline-observation="${item.observation_id || ""}"><time>${formatTime(item.timestamp)}</time><span>${esc(item.kind)}</span><strong>${esc(item.label)}</strong><p>${esc(item.detail)}</p></button>`).join("") || '<p class="empty">No timeline events yet.</p>'; document.querySelectorAll("[data-timeline-observation]").forEach((button) => button.addEventListener("click", () => { const id = Number(button.dataset.timelineObservation); if (id) selectObservation(id); })); }
function renderGraph() { const { nodes, edges, groups } = state.graph; byId("group-count").textContent = `${groups.length} groups / components`; const nodesHtml = nodes.map((node) => `<button class="graph-node" type="button" data-actor-id="${node.id}"><strong>${esc(node.handle)}</strong><span>${node.observation_count} observations · degree ${node.degree}</span><small>Centrality ${node.centrality}</small></button>`).join(""); const edgesHtml = edges.map((edge) => { const safeUrl = safeExternalUrl(edge.evidence_url); return `<a class="graph-edge" href="${esc(safeUrl || "#")}" ${safeUrl ? 'target="_blank" rel="noreferrer"' : ""}><span>${esc(edge.source_handle)} → ${esc(edge.target_handle)}</span><strong>${esc(edge.relation_type)}</strong><small>${Math.round(Number(edge.confidence) * 100)}% · ${formatTime(edge.evidence_timestamp)}</small></a>`; }).join(""); byId("graph").innerHTML = `<div class="node-lane">${nodesHtml || '<p class="empty">No nodes yet.</p>'}</div><div class="edge-lane">${edgesHtml || '<p class="empty">No relationships yet.</p>'}</div>`; document.querySelectorAll("[data-actor-id]").forEach((button) => button.addEventListener("click", () => { const actorId = Number(button.dataset.actorId); const observation = state.observations.find((item) => item.actor_id === actorId); if (observation) selectObservation(observation.id); })); }
function renderProfiles() { byId("profiles").innerHTML = state.profiles.map((profile) => `<article class="profile-card"><div><strong>${esc(profile.handle)}</strong><span>${esc(profile.platform)}</span></div><p>${profile.observation_count} observations · ${profile.snapshot_count} snapshots · ${profile.identity_claim_count} hypotheses</p><small>Average risk ${Number(profile.risk_score).toFixed(1)}</small></article>`).join("") || '<p class="empty">Profiles appear after the first observation.</p>'; }
function renderAssembly() { byId("assembly-grid").innerHTML = state.assembly.map((module) => `<article class="assembly-card"><strong>${esc(module.codename)}</strong><code>${esc(module.model_profile)}</code><p>${esc(module.role)}</p><small>${esc(module.mode)}</small></article>`).join("") || '<p class="empty">Assembly manifest unavailable.</p>'; }
function renderModels() { byId("model-status").innerHTML = state.models.map((model) => `<article class="model-card"><strong>${esc(model.module)}</strong><code>${esc(model.profile)}</code><p>${esc(model.state)} · ${esc(model.dependency)}</p><small>${esc(model.fallback || model.model_download || "local optional")}</small></article>`).join("") || '<p class="empty">Model status unavailable.</p>'; }
function renderAnomalies() { const result = state.anomalies; if (!result) return; const note = `<p class="small-note">${esc(result.note || "")}</p>`; byId("comment-anomalies").innerHTML = result.candidates?.map((item) => `<button type="button" class="finding-card" data-anomaly-observation="${item.observation_id}"><div><strong>${esc(item.actor_handle)}</strong><span class="risk moderate">${Math.round(Number(item.score) * 100)}%</span></div><p>${esc(item.reasons.join(", ") || "statistical outlier")}</p><small>${esc(result.method)} · Review required</small></button>`).join("") + note || note; document.querySelectorAll("[data-anomaly-observation]").forEach((button) => button.addEventListener("click", () => selectObservation(Number(button.dataset.anomalyObservation)))); }
function renderVaults() { byId("vault-runtime").textContent = state.vaultStatus ? `${state.vaultStatus.state} · ${state.vaultStatus.dependency}` : "Runtime unavailable"; byId("vault-list").innerHTML = state.vaults.map((vault) => `<article class="import-item"><strong>${esc(vault.filename)}</strong><span>${esc(vault.state)} · ${formatTime(vault.created_at)}</span><small><button type="button" data-vault-download="${vault.id}">Download</button> · <button type="button" data-vault-verify="${vault.id}">Verify</button></small></article>`).join("") || '<p class="empty">No encrypted export yet.</p>'; document.querySelectorAll("[data-vault-download]").forEach((button) => button.addEventListener("click", async () => { try { await downloadApi(`/api/vaults/${button.dataset.vaultDownload}/download`, "evidence-vault.json"); } catch (error) { setStatus(error.message, true); } })); document.querySelectorAll("[data-vault-verify]").forEach((button) => button.addEventListener("click", async () => { try { const result = await api(`/api/vaults/${button.dataset.vaultVerify}/verify`); await refreshAll(); setStatus(result.state === "valid" ? "Vault signature and ciphertext verified" : result.message, result.state !== "valid"); } catch (error) { setStatus(error.message, true); } })); }
function renderFindings() { byId("findings").innerHTML = state.findings.map((finding) => `<button type="button" class="finding-card" data-finding-observation="${finding.observation_ids?.[0] || ""}"><div><strong>${esc(finding.title)}</strong><span class="risk moderate">${Math.round(Number(finding.confidence) * 100)}%</span></div><p>${esc(finding.summary)}</p><small>${finding.observation_ids?.length || 0} linked observations · ${esc(finding.kind)}</small></button>`).join("") || '<p class="empty">No recurring evidence-backed patterns in this case.</p>'; document.querySelectorAll("[data-finding-observation]").forEach((button) => button.addEventListener("click", () => { const observationId = Number(button.dataset.findingObservation); if (observationId) selectObservation(observationId); })); }
function renderImports() { byId("import-list").innerHTML = state.imports.map((batch) => `<article class="import-item"><strong>${esc(batch.label)}</strong><span>${batch.accepted_count} imported · ${batch.rejected_count} rejected</span><small>${formatTime(batch.created_at)}</small></article>`).join("") || '<p class="empty">No JSON imports in this case.</p>'; }
async function loadCaseData() { if (!state.caseId) return; const [overview, observations, timeline, graph, profiles, processing, findings, imports, anomalies, vaults] = await Promise.all([api(`/api/cases/${state.caseId}`), api(queryPath()), api(`/api/cases/${state.caseId}/timeline`), api(`/api/cases/${state.caseId}/graph`), api(`/api/cases/${state.caseId}/profiles`), api(`/api/cases/${state.caseId}/processing`), api(`/api/cases/${state.caseId}/findings`), api(`/api/cases/${state.caseId}/imports`), api(`/api/cases/${state.caseId}/comment-anomalies`), api(`/api/cases/${state.caseId}/vaults`)]); state.overview = overview; state.observations = observations; state.timeline = timeline; state.graph = graph; state.profiles = profiles; state.processing = processing; state.findings = findings; state.imports = imports; state.anomalies = anomalies; state.vaults = vaults; if (state.detail && !state.observations.some((item) => item.id === state.detail.observation.id)) state.detail = null; renderOverview(); renderObservations(); renderTimeline(); renderGraph(); renderProfiles(); renderProcessing(); renderFindings(); renderImports(); renderAnomalies(); renderVaults(); renderDetail(); }
async function selectCase(caseId) { state.caseId = caseId; state.detail = null; renderCases(); setStatus("Loading case file..."); await loadCaseData(); setStatus("Case file ready"); }
async function selectObservation(id) { state.detail = await api(`/api/observations/${id}`); renderObservations(); renderDetail(); }
async function refreshAll() { setStatus("Refreshing case file..."); state.cases = await api("/api/cases"); renderCases(); await loadCaseData(); setStatus("Case file updated"); }
function relatedHandles(value) { return value.split(",").map((handle) => handle.trim()).filter(Boolean).map((handle) => ({ handle, relation_type: "analyst_link", weight: 0.6 })); }
function renderCommandResult(result) { const node = byId("command-result"); node.hidden = false; const stateNode = byId("command-state"); stateNode.textContent = result.state; stateNode.dataset.error = String(result.state !== "completed"); byId("command-normalized").textContent = result.normalized; byId("command-summary").textContent = result.summary; byId("command-data").textContent = JSON.stringify(result.data, null, 2); const links = byId("command-links"); links.innerHTML = ""; result.links.forEach((item) => { const apiPath = safeApiPath(item.url); if (apiPath) { const button = document.createElement("button"); button.type = "button"; button.textContent = item.label; button.addEventListener("click", async () => { try { if (/\/(export|download)(?:\?|$)/.test(apiPath)) await downloadApi(apiPath); else byId("command-data").textContent = JSON.stringify(await api(apiPath), null, 2); } catch (error) { setStatus(error.message, true); } }); links.appendChild(button); return; } const safeUrl = safeExternalUrl(item.url); if (!safeUrl) return; const link = document.createElement("a"); link.href = safeUrl; link.target = "_blank"; link.rel = "noreferrer"; link.textContent = item.label; links.appendChild(link); }); const next = byId("command-next"); next.innerHTML = ""; result.next_commands.forEach((command) => { const button = document.createElement("button"); button.type = "button"; button.dataset.command = command.replace(/^\//, ""); button.textContent = command; button.addEventListener("click", () => executeCommand(button.dataset.command)); next.appendChild(button); }); }
async function executeCommand(value) { const command = value.trim(); if (!command) return; const rawCommand = command.startsWith("/") ? command : `/${command}`; try { setStatus("Executing local command..."); const result = await api("/api/commands", { method: "POST", body: JSON.stringify({ command: rawCommand, case_id: state.caseId }) }); renderCommandResult(result); if (rawCommand.startsWith("/case create") && result.data?.id) { state.cases = await api("/api/cases"); await selectCase(result.data.id); } else { await refreshAll(); } setStatus(result.state === "completed" ? "Command completed" : "Command unavailable", result.state !== "completed"); } catch (error) { setStatus(error.message, true); } }
function fileToBase64(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(",", 2)[1] || ""); reader.onerror = () => reject(new Error("Local image evidence could not be read.")); reader.readAsDataURL(file); }); }
async function runOcr(evidenceId) { if (!state.caseId || !state.detail) return; if (!window.confirm("Run OCR on this local image evidence? PaddleOCR may download models on the first run.")) return; try { setStatus("GlyphWatch is processing local image evidence..."); const result = await api(`/api/cases/${state.caseId}/evidence/${evidenceId}/ocr`, { method: "POST", body: JSON.stringify({ confirm_model_download: true, language: "en" }) }); await selectObservation(state.detail.observation.id); await loadCaseData(); setStatus(result.state === "completed" ? "OCR result stored for review" : result.message, result.state !== "completed"); } catch (error) { setStatus(error.message, true); } }
byId("new-case-toggle").addEventListener("click", () => { byId("case-form").hidden = !byId("case-form").hidden; });
byId("command-form").addEventListener("submit", (event) => { event.preventDefault(); executeCommand(byId("command-input").value); });
document.querySelectorAll("[data-command]").forEach((button) => button.addEventListener("click", () => executeCommand(button.dataset.command)));
byId("import-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.caseId) return; const form = new FormData(event.currentTarget); try { const parsed = JSON.parse(String(form.get("payload") || "")); const payload = Array.isArray(parsed) ? { items: parsed, label: form.get("label") } : { ...parsed, label: form.get("label") || parsed.label }; setStatus("Import adapter is validating JSON..."); const result = await api(`/api/cases/${state.caseId}/import`, { method: "POST", body: JSON.stringify(payload) }); byId("import-status").textContent = `${result.accepted_count} imported, ${result.rejected_count} rejected.`; event.currentTarget.reset(); await refreshAll(); setStatus("Import completed"); } catch (error) { byId("import-status").textContent = `Import error: ${error.message}`; setStatus(error.message, true); } });
byId("case-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const payload = Object.fromEntries(new FormData(event.currentTarget)); const created = await api("/api/cases", { method: "POST", body: JSON.stringify(payload) }); event.currentTarget.reset(); event.currentTarget.hidden = true; state.cases = await api("/api/cases"); await selectCase(created.id); } catch (error) { setStatus(error.message, true); } });
byId("observation-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.caseId) return; const form = new FormData(event.currentTarget); const timestamp = String(form.get("captured_at") || ""); const sourceTitle = String(form.get("source_title") || "").trim(); const payload = { ...Object.fromEntries(form), captured_at: timestamp ? new Date(timestamp).toISOString() : "", relationships: relatedHandles(String(form.get("related_handles") || "")), sources: sourceTitle ? [{ title: sourceTitle, url: String(form.get("source_link") || ""), excerpt: String(form.get("source_excerpt") || "") }] : [] }; try { setStatus("Collector is processing the observation..."); const created = await api(`/api/cases/${state.caseId}/observations`, { method: "POST", body: JSON.stringify(payload) }); event.currentTarget.reset(); await refreshAll(); await selectObservation(created.observation.id); setStatus("Recorded, linked, and ready for review"); } catch (error) { setStatus(error.message, true); } });
byId("search-input").addEventListener("input", () => loadCaseData().catch((error) => setStatus(error.message, true))); byId("risk-filter").addEventListener("change", () => loadCaseData().catch((error) => setStatus(error.message, true))); byId("refresh-all").addEventListener("click", () => refreshAll().catch((error) => setStatus(error.message, true)));
byId("seed-demo").addEventListener("click", async () => { try { setStatus("Loading demo data..."); await api("/api/seed", { method: "POST", body: "{}" }); await refreshAll(); setStatus("Demo data ready"); } catch (error) { setStatus(error.message, true); } });
byId("generate-draft").addEventListener("click", async () => { if (!state.detail) return; try { setStatus("Creating draft..."); state.detail = await api(`/api/observations/${state.detail.observation.id}/draft`, { method: "POST", body: JSON.stringify({ tone: "firm" }) }); renderDetail(); setStatus("Draft ready for human review"); } catch (error) { setStatus(error.message, true); } });
byId("note-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.detail) return; try { await api(`/api/cases/${state.caseId}/notes`, { method: "POST", body: JSON.stringify({ body: new FormData(event.currentTarget).get("body"), observation_id: state.detail.observation.id }) }); event.currentTarget.reset(); await loadCaseData(); setStatus("Note saved"); } catch (error) { setStatus(error.message, true); } });
byId("screenshot-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.detail) return; try { const form = new FormData(event.currentTarget); await api(`/api/cases/${state.caseId}/screenshots`, { method: "POST", body: JSON.stringify({ label: form.get("label"), url: form.get("url"), observation_id: state.detail.observation.id }) }); event.currentTarget.reset(); await selectObservation(state.detail.observation.id); await loadCaseData(); setStatus("Screenshot reference saved"); } catch (error) { setStatus(error.message, true); } });
byId("local-image-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.detail) return; try { const form = new FormData(event.currentTarget); const image = form.get("image"); if (!(image instanceof File) || !image.size) throw new Error("Select local image evidence."); if (image.size > 8 * 1024 * 1024) throw new Error("Local image evidence must not exceed 8 MB."); setStatus("Storing local image evidence..."); await api(`/api/cases/${state.caseId}/local-media`, { method: "POST", body: JSON.stringify({ label: form.get("label"), observation_id: state.detail.observation.id, content_base64: await fileToBase64(image) }) }); event.currentTarget.reset(); await selectObservation(state.detail.observation.id); setStatus("Local image evidence stored; OCR remains opt-in."); } catch (error) { setStatus(error.message, true); } });
byId("vault-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.caseId) return; const form = new FormData(event.currentTarget); const passphrase = String(form.get("passphrase") || ""); if (passphrase.length < 16) { setStatus("Vault passphrase must contain at least 16 characters.", true); return; } if (!window.confirm("Create a signed and encrypted local export for this case? The passphrase is not stored.")) return; try { setStatus("EvidenceVault is sealing the case file..."); const created = await api(`/api/cases/${state.caseId}/vault`, { method: "POST", body: JSON.stringify({ operator: form.get("operator"), passphrase, confirm: true }) }); event.currentTarget.reset(); await refreshAll(); setStatus(`EvidenceVault created: ${created.filename}`); } catch (error) { setStatus(error.message, true); } });
byId("identity-form").addEventListener("submit", async (event) => { event.preventDefault(); if (!state.detail) return; try { const payload = Object.fromEntries(new FormData(event.currentTarget)); payload.actor_id = state.detail.actor.id; payload.evidence_observation_id = state.detail.observation.id; await api(`/api/cases/${state.caseId}/identity-claims`, { method: "POST", body: JSON.stringify(payload) }); event.currentTarget.reset(); await refreshAll(); setStatus("Hypothesis and confidence saved"); } catch (error) { setStatus(error.message, true); } });
byId("export-json").addEventListener("click", async () => { if (!state.caseId) return; try { await downloadApi(`/api/cases/${state.caseId}/export?format=json`, `signal-desk-case-${state.caseId}.json`); } catch (error) { setStatus(error.message, true); } }); byId("export-pdf").addEventListener("click", async () => { if (!state.caseId) return; try { await downloadApi(`/api/cases/${state.caseId}/export?format=pdf`, `signal-desk-case-${state.caseId}.pdf`); } catch (error) { setStatus(error.message, true); } });
(async () => { try { const [assembly, models, vaultStatus, cases] = await Promise.all([api("/api/assembly"), api("/api/models"), api("/api/vault/status"), api("/api/cases")]); state.assembly = assembly; state.models = models; state.vaultStatus = vaultStatus; state.cases = cases; state.caseId = state.cases[0]?.id || null; renderAssembly(); renderModels(); renderCases(); await loadCaseData(); setStatus("SithAssembly//Instawatch ready"); } catch (error) { setStatus(error.message, true); } })();
